### ISSUE TITLE
refactoring kafka connector to conform to DataSource and DataSink API

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#1098]
Task list:

- [x] allow user to configure kafka through API (#1053)
- [x] refactoring KafkaSource and KafkaSink to conform to DataSource and DataSink API (#1115)
- [x] decoupling KafkaStorage from KafkaSource (#438)
- [ ] add documentations for DataSource and DataSink and update kafka docs on README and gearpump.io
