### ISSUE TITLE
Gearpump Security

### ISSUE THREAD

**Issue by clockfly** [gearpump/gearpump#1247]
This is an umbrella for multi-tenancy related issues.
- [x] user management. Authentication/authorization/audit
- [ ] #1074   It shouldn't be possible to disturb akka clustering mechanism that is used in multi-master configuration feature P2 security
- [x] #1073		It shouldn't be possible to look at the other org’s applications in services console feature P2 security
- [ ] #1072		It shouldn't be possible to send messages to other org’s actors feature P2 security
- [ ] #1071		It shouldn't be possible to sniff other org’s communication between actors feature P2 security
- [x] #1070		It shouldn't be possible to kill other org’s GP instance. feature P2 security
- [x] #1069		Gearpump multitenancy in context of security feature P2 security
- [ ] #1458                Gearpump Kerberos Support

**Comment by clockfly** [comment]
For the new UI with authentication, please see demo at http://52.53.210.64:8090/

**Comment by manuzhang** [comment]
"SignOut" is not shown on mobine
![screenshot_2016-01-14-19-41-29_com android chrome](https://cloud.githubusercontent.com/assets/1191767/12323574/8186be18-baf7-11e5-8ee2-7b92c19cc2e0.png)

**Comment by clockfly** [comment]
@manuzhang 
 fixed in PR #1867

**Comment by manuzhang** [comment]
migrated to https://issues.apache.org/jira/browse/GEARPUMP-74
