### ISSUE TITLE
storm compatibility 

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#1386]
We are aiming at providing binary compatibility for storm applications over gearpump and here is a checklist for achieving this goal. 

- [x] basic storm connector (#415)
- [x] shell spout / bolt support (#924) (*work around*)
- [x] tag storm tuple with timestamp (#1324)
- [x] tick tuple support (#1379)
- [x] emitDirect and DirectGrouping (#1343, depends on #1373 and #1377)
- [x] AllGrouping (depends on #1238)
- [x] CustomSerializerGrouping and CustomObjectGrouping (#1442)
- [x] meaningful ack and fail in gearpump (currently no-op)
- [ ] write a blog to introduce this feature
