### ISSUE TITLE
Some UI features requirements 

### ISSUE THREAD

**Issue by clockfly** [gearpump/gearpump#1678]
*Metrics Service*
- [x]  UI should scale better. (#1499)
- [x]  Allow switch charts to show current metrics and historical metrics (#1411)
- [ ] Provide summary path information for any two points selected in the DAG (#875)
- [x] Show effective message receive latency over message paths (#1779)

*Usability*
- [x]  Allow user to submit a storm jar by UI. (#1648)
- [ ]  Allow user to submit multiple jars when composing the DAG. (#1450)
- [x]  Allow user to change the transition time when changing the parallelism. (#1682)
- [ ]  Allow user to submit config when replacing a processor. (#1366)
- [x]  Textual Changes: (#1691)
 1. Change "Receive Throughput Skew" to "Task Receive throughput", or some better
 2. Still show the above graph if only one task is present.
 3. Change "Task Selector" to "Pick one task to see its detail metrics..."or some better
 4. Summary page, use (s): 2 processor -> processors ,  executor -> executors
 5. Add a document link at the right corner. Along with the source code link.

*AppMaster*
- [ ]  Able to see history job status.
- [x]  Show error status in Application page. (#1681)

*Security*
- [x]  Authentication/authorization.
- [x] Add a security configuration options to disable all HTTP POST, DELETE, and PUT, so that we can host gearpump demo on public server. 

*Cluster managerment*
- [ ] Allow admin to add/remove a worker, add/remove a master.

**Comment by manuzhang** [comment]
Some minor suggestions.

1. Could we have configs shown in a three-column table (name, value, origin) ?
2. On the submit DAG console, `submit` is placed to the left of `cancel`. Is it more user friendly (more common) to place `submit` right to `cancel` (just like the `Close and comment` and `Comment` buttons here).
3. On dynamic change, do we show which executors are alive and which are not ?

**Comment by stanleyxu2005** [comment]
@manuzhang I've 2 comments on your suggestions:
1. Akka's configuration is HConf format. Currently there is no frontend tool to highlight such format. If backend can convert it into a nested structure as you described, we can update the configuration viewer as you expected.
2. I followed the classic UI design language, that "Cancel" button is at right. The reason is that submission can be complex, you need to input many things before click "Submit" button. But if you want to close a dialog quick, the more intuitive position is always the most right side.

**Comment by manuzhang** [comment]
about no.2. I don't know about the design language but I've seen @huafengw added a jar file and then quickly closed the console although he meant to submit. It's a minor issue though.

**Comment by manuzhang** [comment]
@stanleyxu2005 
Please refer to the "Iteration" section of `Config` API
`Config.root.unwrapped`
> Recursively unwraps the object, returning a map from String to whatever plain Java values are unwrapped from the object's values.

**Comment by clockfly** [comment]
@manuzhang 
I disagree with these two columns key-value style display. I think tree-like display style looks better.

**Comment by stanleyxu2005** [comment]
Actually it is key, value, default value, description. If it config can be retrieved in this way, yes. we can provide a read-only configuration viewer.

**Comment by clockfly** [comment]
Add two new requirement:
1.  Add a security configuration options to disable all HTTP POST, DELETE, and PUT, so that we can host gearpump demo on public server.
2. Allow admin to add/remove a worker, add/remove a master.

**Comment by stanleyxu2005** [comment]
If I understand new feature 1 correctly, that disabling particular operations means to have a guest account that can only view cluster information.

**Comment by manuzhang** [comment]
All features here have been migrated to Apache Jira as below.
feature | Apache Jira
--------- | --------------
Able to see history job status | https://issues.apache.org/jira/browse/GEARPUMP-92
Allow admin to add/remove a worker, add/remove a master | https://issues.apache.org/jira/browse/GEARPUMP-93
Could we have configs shown in a three-column table (name, value, origin) and allow users to search ? | https://issues.apache.org/jira/browse/GEARPUMP-94
